management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netlix: warn
    com.springframwork.web: warn
    com.github: debug
